import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/app/theme-provider";
import { ModeSwitch } from "~/app/theme-selector";
import { BoxIcon, RocketIcon, VercelLogoIcon } from "@radix-ui/react-icons";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";
import { Avatar, AvatarFallback, AvatarImage } from "~/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "~/components/ui/tooltip";
import Link from "next/link";
import Home from "./page";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} bg-muted/40`}>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex">
              <aside className="inset-y-0 left-0 z-10 hidden w-14 flex-col border-r bg-background sm:flex">
                <nav className="flex flex-col items-center gap-6 px-3 sm:py-6">
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger>
                        <VercelLogoIcon
                          className="h-4 w-4 transition-all group-hover:scale-110"
                          aria-label="app logo"
                        />
                        <span className="sr-only">App Name</span>
                      </TooltipTrigger>
                      <TooltipContent side="right">App Name</TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                  <div className="flex flex-col gap-3">
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Link
                            href="#"
                            className="group flex h-9 w-9 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:h-8 md:w-8 md:text-base"
                          >
                            <RocketIcon
                              className="h-4 w-4 transition-all group-hover:scale-110"
                              aria-label="launch pad"
                            />
                            <span className="sr-only">Acme Inc</span>
                          </Link>
                        </TooltipTrigger>
                        <TooltipContent side="right">Dashboard</TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                    <Link
                      href="#"
                      className="group flex h-9 w-9 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:h-8 md:w-8 md:text-base"
                    >
                      <BoxIcon
                        className="h-4 w-4 transition-all group-hover:scale-110"
                        aria-label="play books"
                      />
                      <span className="sr-only">Acme Inc</span>
                    </Link>
                  </div>
                </nav>
              </aside>
              <div className="flex w-full flex-col gap-3">
                <div className="flex p-3 xl:justify-between">
                  <div className="flex flex-col items-center">
                    <div className="flex items-center gap-3">
                      <Select value="A">
                        <SelectTrigger className="w-[180px] bg-background">
                          <SelectValue placeholder="Select a workspace" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectGroup>
                            <SelectLabel>Workspaces</SelectLabel>
                            <SelectItem value="A">A</SelectItem>
                            <SelectItem value="B">B</SelectItem>
                            <SelectItem value="C">C</SelectItem>
                          </SelectGroup>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Avatar className="cursor-pointer">
                          <AvatarImage
                            src="https://github.com/shadcn.png"
                            alt="@shadcn"
                          />
                          <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent className="w-56 px-5 py-3">
                        <ModeSwitch />
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
                <div className="min-h-svh">{children}</div>
              </div>
            </div>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
